#!/bin/bash
FILE_OFF=/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini.off
FILE_ON=/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

if test -f "$FILE_ON"; then
    sudo mv $FILE_ON $FILE_OFF && kill -USR2 1
    echo -e "XDEBUG \e[91mdesabilitado! \e[39m"
fi